this.fanvas=this.fanvas||{};
(function(){var e=[];fanvas.imageList={};fanvas.indexOf=function(a,c){for(var d=0,f=a.length;d<f;d++)if(c===a[d])return d;return-1};fanvas.indexOfCanvas=function(a,c){for(var d=0,f=a.length;d<f;d++)if(a[d].canvas&&c===a[d].canvas)return d;return-1};fanvas.play=function(a,c,d){if(!(0<=fanvas.indexOfCanvas(e,a))&&c){var f=function(){var f={canvas:a,config:d,frame:0};e.push(f);f.stage=new fanvas.Stage(a,c,d);var b=function(a){f.stage.update(a);f.frame++;if(d.onFrame)d.onFrame(f.frame);0==d.autoPlay&&
(f.timer.pause(),d.autoPlay=!0)};f.timer=new fanvas.Timer(c.frameRate,b);f.timer.start();b(0)};d=d||{};var b=d.imagePath||"";if(c.images){for(var g=[],n=0;n<c.images.length;n++)g.push(b+c.images[n]);(new fanvas.Preloader).load(g,fanvas.imageList,f)}else f()}};fanvas.replay=function(a){a=fanvas.indexOfCanvas(e,a);0<=a&&(e[a].frame=0,e[a].stage.replay(),e[a].timer.resume())};fanvas.pause=function(a){a=fanvas.indexOfCanvas(e,a);0<=a&&e[a].timer.pause()};fanvas.resume=function(a){a=fanvas.indexOfCanvas(e,
a);0<=a&&e[a].timer.resume()};var b=function(a,c,d){a=fanvas.indexOfCanvas(e,a);if(0<=a){e[a].timer.pause();c<e[a].frame&&(e[a].stage.replay(),e[a].frame=0);for(var f=c-e[a].frame-1,b=0;b<f;b++)e[a].stage.update(0,!0);0<=f&&e[a].stage.update(0,!1);e[a].frame=c;d||e[a].timer.resume()}};fanvas.gotoAndPlay=function(a,c){b(a,c)};fanvas.gotoAndStop=function(a,c){b(a,c,!0)}})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,c){this.initialize(a,c)},b=e.prototype;b.interval=16;b.onFrame=null;b.paused=!1;b._stop=!1;b.initialize=function(a,c){if(0>=a||!c)throw"err";this.interval=Math.floor(1E3/a);this.onFrame=c};window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;b.start=function(){var a=Date.now(),c=Date.now(),d=this,f=function(){if(d.paused)d._stop=!0;else{var b=Date.now(),g=b-a,n=b-
c;window.requestAnimationFrame?(requestAnimationFrame(f),g>d.interval&&(a=b-g%d.interval,c=b,d.onFrame(n))):(setTimeout(f,d.interval),a=b,d.onFrame(g))}};f()};b.pause=function(){this.paused=!0};b.resume=function(){this.paused&&(this.paused=!1,this._stop&&(this._stop=!1,this.start()))};fanvas.Timer=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a){this.initialize(a)},b=e.prototype;b.ctx=null;b.maxFPS=0;b.minFPS=99;b.frameCount=0;b.totalDelta=0;b.fps=0;b.initialize=function(a){this.ctx=a};b.update=function(a){this.totalDelta+=a;this.frameCount++;1E3<this.totalDelta&&(a=this.fps=this.frameCount,this.frameCount=this.totalDelta=0,a>this.maxFPS&&(this.maxFPS=a),a<this.minFPS&&(this.minFPS=a));a=this.ctx;a.beginPath();a.rect(0,0,48,48);a.fillStyle="#000";a.fill();a.fillStyle="#FFFFFF";a.fillText("FPS: "+this.fps,5,13);
a.fillText("Max: "+this.maxFPS,5,27);a.fillText("Min: "+this.minFPS,5,41)};fanvas.Stats=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(){this.initialize()},b=e.prototype;b._taskCount=0;b._finishCount=0;b._callback=null;b.initialize=function(){};b.load=function(a,c,d){0==a.length&&d();this._taskCount=a.length;this._finishCount=0;for(var f=this,b=0;b<a.length;b++){var g=document.createElement("img");g.onload=function(){f._finishCount++;f._finishCount==f._taskCount&&d()};g.src=a[b];c[a[b]]=g}};fanvas.Preloader=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,c,d,f,b,g){this.initialize(a,c,d,f,b,g)},b=e.prototype;e.identity=null;e.DEG_TO_RAD=Math.PI/180;b.a=1;b.b=0;b.c=0;b.d=1;b.tx=0;b.ty=0;b.alpha=1;b.shadow=null;b.compositeOperation=null;b.visible=!0;b.initialize=function(a,c,d,b,h,g){this.a=null==a?1:a;this.b=c||0;this.c=d||0;this.d=null==b?1:b;this.tx=h||0;this.ty=g||0;return this};b.prepend=function(a,c,d,b,h,g){var f=this.tx;if(1!=a||0!=c||0!=d||1!=b){var e=this.a,q=this.c;this.a=e*a+this.b*d;this.b=e*c+this.b*b;this.c=
q*a+this.d*d;this.d=q*c+this.d*b}this.tx=f*a+this.ty*d+h;this.ty=f*c+this.ty*b+g;return this};b.append=function(a,c,d,b,h,g){var f=this.a,e=this.b,q=this.c,w=this.d;this.a=a*f+c*q;this.b=a*e+c*w;this.c=d*f+b*q;this.d=d*e+b*w;this.tx=h*f+g*q+this.tx;this.ty=h*e+g*w+this.ty;return this};b.prependMatrix=function(a){this.prepend(a.a,a.b,a.c,a.d,a.tx,a.ty);this.prependProperties(a.alpha,a.shadow,a.compositeOperation,a.visible);return this};b.appendMatrix=function(a){this.append(a.a,a.b,a.c,a.d,a.tx,a.ty);
this.appendProperties(a.alpha,a.shadow,a.compositeOperation,a.visible);return this};b.prependTransform=function(a,c,d,b,h,g,n,l,q){if(h%360){var f=h*e.DEG_TO_RAD;h=Math.cos(f);f=Math.sin(f)}else h=1,f=0;if(l||q)this.tx-=l,this.ty-=q;g||n?(g*=e.DEG_TO_RAD,n*=e.DEG_TO_RAD,this.prepend(h*d,f*d,-f*b,h*b,0,0),this.prepend(Math.cos(n),Math.sin(n),-Math.sin(g),Math.cos(g),a,c)):this.prepend(h*d,f*d,-f*b,h*b,a,c);return this};b.appendTransform=function(a,c,d,b,h,g,n,l,q){if(h%360){var f=h*e.DEG_TO_RAD;h=
Math.cos(f);f=Math.sin(f)}else h=1,f=0;g||n?(g*=e.DEG_TO_RAD,n*=e.DEG_TO_RAD,this.append(Math.cos(n),Math.sin(n),-Math.sin(g),Math.cos(g),a,c),this.append(h*d,f*d,-f*b,h*b,0,0)):this.append(h*d,f*d,-f*b,h*b,a,c);if(l||q)this.tx-=l*this.a+q*this.c,this.ty-=l*this.b+q*this.d;return this};b.rotate=function(a){var c=Math.cos(a);a=Math.sin(a);var d=this.a,b=this.c,h=this.tx;this.a=d*c-this.b*a;this.b=d*a+this.b*c;this.c=b*c-this.d*a;this.d=b*a+this.d*c;this.tx=h*c-this.ty*a;this.ty=h*a+this.ty*c;return this};
b.skew=function(a,c){a*=e.DEG_TO_RAD;c*=e.DEG_TO_RAD;this.append(Math.cos(c),Math.sin(c),-Math.sin(a),Math.cos(a),0,0);return this};b.scale=function(a,c){this.a*=a;this.d*=c;this.c*=a;this.b*=c;this.tx*=a;this.ty*=c;return this};b.translate=function(a,c){this.tx+=a;this.ty+=c;return this};b.identity=function(){this.alpha=this.a=this.d=1;this.b=this.c=this.tx=this.ty=0;this.shadow=this.compositeOperation=null;this.visible=!0;return this};b.invert=function(){var a=this.a,c=this.b,d=this.c,b=this.d,
h=this.tx,g=a*b-c*d;this.a=b/g;this.b=-c/g;this.c=-d/g;this.d=a/g;this.tx=(d*this.ty-b*h)/g;this.ty=-(a*this.ty-c*h)/g;return this};b.appendProperties=function(a,c,b,f){this.alpha*=a;this.shadow=c||this.shadow;this.compositeOperation=b||this.compositeOperation;this.visible=this.visible&&f;return this};b.prependProperties=function(a,c,b,f){this.alpha*=a;this.shadow=this.shadow||c;this.compositeOperation=this.compositeOperation||b;this.visible=this.visible&&f;return this};e.identity=new e;fanvas.Matrix2D=
e})();this.fanvas=this.fanvas||{};(function(){var e=function(a,c,b,f){this.initialize(a,c,b,f)},b=e.prototype;b.x=0;b.y=0;b.width=0;b.height=0;b.initialize=function(a,c,b,f){this.x=a||0;this.y=c||0;this.width=b||0;this.height=f||0;return this};fanvas.Rectangle=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,c,b,f){this.initialize(a,c,b,f)},b=e.prototype;b.color=null;b.offsetX=0;b.offsetY=0;b.blur=0;b.initialize=function(a,c,b,f){this.color=a;this.offsetX=c||0;this.offsetY=b||0;this.blur=f};e.identity=new e("transparent",0,0,0);fanvas.Shadow=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(){this.initialize()},b=e.prototype;b.alpha=1;b.cacheCanvas=null;b.name=null;b.parent=null;b.root=null;b.regX=0;b.regY=0;b.rotation=0;b.scaleX=1;b.scaleY=1;b.skewX=0;b.skewY=0;b.shadow=null;b.visible=!0;b.x=0;b.y=0;b.rect=null;b.initFrame=-1;b.compositeOperation=null;b.filters=null;b.mask=null;b.clipDepth=0;b.maskDepth=0;b._cacheOffsetX=0;b._cacheOffsetY=0;b._cacheScale=1;b._matrix=null;b.globalMatrix=null;b.dirtyRect=null;b.initialize=function(){this._matrix=new fanvas.Matrix2D;
this.globalMatrix=new fanvas.Matrix2D};b.isVisible=function(){return!(!(this.visible&&0<this.alpha&&0!=this.scaleX&&0!=this.scaleY)||this.clipDepth)};b.drawFromCache=function(a){var c=this.cacheCanvas;if(!c)return!1;var b=this._cacheScale,f=this._cacheOffsetX,h=this._cacheOffsetY,g;if(g=this._applyFilterBounds(f,h,0,0))f=g.x,h=g.y;a.drawImage(c,f,h,c.width/b,c.height/b);return!0};b.update=function(){};b.calculateDirtyRect=function(){this.parent&&(this.globalMatrix=new fanvas.Matrix2D,this.globalMatrix.appendTransform(this.x,
this.y,this.scaleX,this.scaleY,this.rotation,this.skewX,this.skewY,this.regX,this.regY).prependMatrix(this.parent.globalMatrix));var a=this.rect,c=this._applyFilterBounds(a.x,a.y,a.width,a.height);return this.dirtyRect=this._transformBounds(c||a,this.globalMatrix)};b.presetContext=function(a){var c,b=this.mask;b&&b.graphics&&!b.graphics.isEmpty()&&(c=b.getMatrix(b._matrix),a.transform(c.a,c.b,c.c,c.d,c.tx,c.ty),b.graphics.drawAsPath(a),a.clip(),c.invert(),a.transform(c.a,c.b,c.c,c.d,c.tx,c.ty));c=
this._matrix.identity().appendTransform(this.x,this.y,this.scaleX,this.scaleY,this.rotation,this.skewX,this.skewY,this.regX,this.regY);a.transform(c.a,c.b,c.c,c.d,Math.round(c.tx),Math.round(c.ty));a.globalAlpha*=this.alpha;this.compositeOperation&&(a.globalCompositeOperation=this.compositeOperation);this.shadow&&this._applyShadow(a,this.shadow)};b.cache=function(a,c,b,f,h){h=h||1;this.cacheCanvas||(this.cacheCanvas=document.createElement("canvas"));this._cacheWidth=b;this._cacheHeight=f;this._cacheOffsetX=
a;this._cacheOffsetY=c;this._cacheScale=h;this.updateCache()};b.updateCache=function(a){var c=this.cacheCanvas,b=this._cacheScale,f=this._cacheOffsetX*b,h=this._cacheOffsetY*b,g=this._cacheWidth,e=this._cacheHeight,l;if(c){var q=c.getContext("2d");if(l=this._applyFilterBounds(f,h,g,e))f=l.x,h=l.y,g=l.width,e=l.height;g=Math.ceil(g*b);e=Math.ceil(e*b);g!=c.width||e!=c.height?(c.width=g,c.height=e):a||q.clearRect(0,0,g+1,e+1);q.save();q.globalCompositeOperation=a;q.setTransform(b,0,0,b,-f,-h);this.draw(q,
!0);this._applyFilters();q.restore()}};b.uncache=function(){this.cacheCanvas=null;this._cacheOffsetX=this._cacheOffsetY=0;this._cacheScale=1};b.setTransform=function(a,c,b,f,h,e,n,l,q){this.x=a||0;this.y=c||0;this.scaleX=0==b||b?b:1;this.scaleY=0==f||f?f:1;this.rotation=h||0;this.skewX=e||0;this.skewY=n||0;this.regX=l||0;this.regY=q||0};b.getMatrix=function(a){return(a?a.identity():new fanvas.Matrix2D).appendTransform(this.x,this.y,this.scaleX,this.scaleY,this.rotation,this.skewX,this.skewY,this.regX,
this.regY).appendProperties(this.alpha,this.shadow,this.compositeOperation)};b._applyShadow=function(a,c){c=c||Shadow.identity;a.shadowColor=c.color;a.shadowOffsetX=c.offsetX;a.shadowOffsetY=c.offsetY;a.shadowBlur=c.blur};b._applyFilters=function(){if(this.filters&&0!=this.filters.length&&this.cacheCanvas)for(var a=this.filters.length,c=this.cacheCanvas.getContext("2d"),b=this.cacheCanvas.width,f=this.cacheCanvas.height,h=0;h<a;h++)this.filters[h].applyFilter(c,0,0,b,f)};b._applyFilterBounds=function(a,
c,b,f){var d,e,n=this.filters;if(!n||!(e=n.length))return null;for(n=0;n<e;n++){var l=this.filters[n];if(l=l.getBounds&&l.getBounds())d||(d=new fanvas.Rectangle(a,c,b,f)),d.x+=l.x,d.y+=l.y,d.width+=l.width,d.height+=l.height}return d};b._transformBounds=function(a,c){var b=a.x,f=a.y,h=a.width,e=a.height,n=new fanvas.Matrix2D;n.appendMatrix(c);(b||f)&&n.append(1,0,0,1,b,f);c=h*n.a;h*=n.b;a=e*n.c;var e=e*n.d,l=n.tx,n=n.ty,q=l,w=l,r=n,k=n;(b=c+l)<q?q=b:b>w&&(w=b);(b=c+a+l)<q?q=b:b>w&&(w=b);(b=a+l)<q?
q=b:b>w&&(w=b);(f=h+n)<r?r=f:f>k&&(k=f);(f=h+e+n)<r?r=f:f>k&&(k=f);(f=e+n)<r?r=f:f>k&&(k=f);return new fanvas.Rectangle(Math.round(q),Math.round(r),Math.round(w-q),Math.round(k-r))};fanvas.DisplayObject=e})();this.fanvas=this.fanvas||{};
(function(){function e(a,c,b){this.f=a;this.params=c;this.isPath=!!b}e.prototype.exec=function(a){this.f.apply(a,this.params)};var b=function(a){this.initialize(a)},a=b.prototype;b.BASE_64={A:0,B:1,C:2,D:3,E:4,F:5,G:6,H:7,I:8,J:9,K:10,L:11,M:12,N:13,O:14,P:15,Q:16,R:17,S:18,T:19,U:20,V:21,W:22,X:23,Y:24,Z:25,a:26,b:27,c:28,d:29,e:30,f:31,g:32,h:33,i:34,j:35,k:36,l:37,m:38,n:39,o:40,p:41,q:42,r:43,s:44,t:45,u:46,v:47,w:48,x:49,y:50,z:51,0:52,1:53,2:54,3:55,4:56,5:57,6:58,7:59,8:60,9:61,"+":62,"/":63};
var c=document.createElement("canvas");if(c.getContext){var d=b._ctx=c.getContext("2d");b.beginCmd=new e(d.beginPath,[]);b.fillCmd=new e(d.fill,["evenodd"]);b.strokeCmd=new e(d.stroke,[]);c.width=c.height=1}a._imagePath=null;a._strokeInstructions=null;a._strokeStyleInstructions=null;a._fillInstructions=null;a._fillMatrix=null;a._instructions=null;a._activeInstructions=null;a._active=!1;a._dirty=!1;a.initialize=function(a){this.clear();this._ctx=b._ctx;this._imagePath=a};a.isEmpty=function(){return!(this._instructions.length||
this._activeInstructions.length)};a.draw=function(a){this._dirty&&this._updateInstructions();for(var c=this._instructions,b=0,f=c.length;b<f;b++)c[b].exec(a)};a.drawAsPath=function(a){this._dirty&&this._updateInstructions();for(var c,b=this._instructions,f=0,d=b.length;f<d;f++)((c=b[f]).isPath||0==f)&&c.exec(a)};a.moveTo=function(a,c){this._activeInstructions.push(new e(this._ctx.moveTo,[a,c],!0))};a.lineTo=function(a,c){this._dirty=this._active=!0;this._activeInstructions.push(new e(this._ctx.lineTo,
[a,c],!0))};a.quadraticCurveTo=function(a,c,b,d){this._dirty=this._active=!0;this._activeInstructions.push(new e(this._ctx.quadraticCurveTo,[a,c,b,d],!0))};a.bezierCurveTo=function(a,c,b,d,l,q){this._dirty=this._active=!0;this._activeInstructions.push(new e(this._ctx.bezierCurveTo,[a,c,b,d,l,q],!0))};a.closePath=function(){this._active&&(this._dirty=!0,this._activeInstructions.push(new e(this._ctx.closePath,[],!0)))};a.clear=function(){this._instructions=[];this._activeInstructions=[];this._strokeStyleInstructions=
this._strokeInstructions=this._fillInstructions=this._fillMatrix=null;this._active=this._dirty=!1};a.beginFill=function(a){this._active&&this._newPath();this._fillInstructions=a?[new e(this._setProp,["fillStyle",a])]:null;this._fillMatrix=null};a.beginLinearGradientFill=function(a,c,b,d,l,q){this._active&&this._newPath();b=this._ctx.createLinearGradient(b,d,l,q);d=0;for(l=a.length;d<l;d++)b.addColorStop(c[d],a[d]);this._fillInstructions=[new e(this._setProp,["fillStyle",b])];this._fillMatrix=null};
a.beginRadialGradientFill=function(a,c,b,d,l,q,w,r){this._active&&this._newPath();b=this._ctx.createRadialGradient(b,d,l,q,w,r);d=0;for(l=a.length;d<l;d++)b.addColorStop(c[d],a[d]);this._fillInstructions=[new e(this._setProp,["fillStyle",b])];this._fillMatrix=null};a.beginBitmapFill=function(a,c){this._active&&this._newPath();a=this._ctx.createPattern(fanvas.imageList[this._imagePath+a],"");this._fillInstructions=[new e(this._setProp,["fillStyle",a],!1)];this._fillMatrix=c};a.endFill=function(){this.beginFill()};
a.setStrokeStyle=function(a,c,b,d){this._active&&this._newPath();this._strokeStyleInstructions=[new e(this._setProp,["lineWidth",null==a?"1":a]),new e(this._setProp,["lineCap",null==c?"butt":c]),new e(this._setProp,["lineJoin",null==b?"miter":b]),new e(this._setProp,["miterLimit",null==d?"10":d])];return this};a.beginStroke=function(a){this._active&&this._newPath();this._strokeInstructions=a?[new e(this._setProp,["strokeStyle",a])]:null};a.beginLinearGradientStroke=function(a,c,b,d,l,q){this._active&&
this._newPath();b=this._ctx.createLinearGradient(b,d,l,q);d=0;for(l=a.length;d<l;d++)b.addColorStop(c[d],a[d]);this._strokeInstructions=[new e(this._setProp,["strokeStyle",b])]};a.beginRadialGradientStroke=function(a,c,b,d,l,q,w,r){this._active&&this._newPath();b=this._ctx.createRadialGradient(b,d,l,q,w,r);d=0;for(l=a.length;d<l;d++)b.addColorStop(c[d],a[d]);this._strokeInstructions=[new e(this._setProp,["strokeStyle",b])]};a.endStroke=function(){this.beginStroke()};a.decodePath=function(a){for(var c=
[this.moveTo,this.lineTo,this.quadraticCurveTo,this.bezierCurveTo,this.closePath],d=[2,2,4,6,0],f=0,e=a.length,q=[],w=0,r=0,k=b.BASE_64;f<e;){var m=a.charAt(f),p=k[m],u=p>>3,t=c[u];if(!t||p&3)throw"bad path data (@"+f+"): "+m;m=d[u];u||(w=r=0);q.length=0;f++;p=(p>>2&1)+2;for(u=0;u<m;u++){var x=k[a.charAt(f)],y=x>>5?-1:1,x=(x&31)<<6|k[a.charAt(f+1)];3==p&&(x=x<<6|k[a.charAt(f+2)]);x=y*x/10;u%2?w=x+=w:r=x+=r;q[u]=x;f+=p}t.apply(this,q)}};a.c=a.clear;a.f=a.beginFill;a.lf=a.beginLinearGradientFill;a.rf=
a.beginRadialGradientFill;a.bf=a.beginBitmapFill;a.ef=a.endFill;a.ss=a.setStrokeStyle;a.s=a.beginStroke;a.ls=a.beginLinearGradientStroke;a.rs=a.beginRadialGradientStroke;a.es=a.endStroke;a.p=a.decodePath;a._updateInstructions=function(){this._instructions.push(b.beginCmd);this._appendInstructions(this._fillInstructions);this._strokeInstructions&&(this._appendInstructions(this._strokeInstructions),this._appendInstructions(this._strokeStyleInstructions));this._appendInstructions(this._activeInstructions);
this._fillInstructions&&this._appendDraw(b.fillCmd,this._fillMatrix);this._strokeInstructions&&this._instructions.push(b.strokeCmd)};a._appendInstructions=function(a){a&&this._instructions.push.apply(this._instructions,a)};a._appendDraw=function(a,c){c?this._instructions.push(new e(this._ctx.save,[],!1),new e(this._ctx.transform,c,!1),a,new e(this._ctx.restore,[],!1)):this._instructions.push(a)};a._newPath=function(){this._dirty&&this._updateInstructions();this._activeInstructions=[];this._active=
this._dirty=!1};a._setProp=function(a,c){this[a]=c};fanvas.Graphics=b})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,c){this.initialize(a,c)},b=e.prototype=new fanvas.DisplayObject;b.graphics=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(a,c){this.DisplayObject_initialize();if(a instanceof fanvas.Graphics)this.graphics=a;else for(this.graphics=new fanvas.Graphics(c.imagePath||""),c=0;c<a.length;c++)this.graphics[a[c][0]].apply(this.graphics,a[c].slice(1))};b.draw=function(a,c){if(!c&&this.drawFromCache(a))return!0;this.graphics.draw(a);return!0};fanvas.Shape=e})();
this.fanvas=this.fanvas||{};
(function(){var e=function(){this.initialize()},b=e.prototype=new fanvas.DisplayObject;b.children=null;b.DisplayObject_initialize=b.initialize;b.initialize=function(){this.DisplayObject_initialize();this.children=[]};b.DisplayObject_draw=b.draw;b.DisplayObject_update=b.update;b.draw=function(a,c){if(!c&&this.drawFromCache(a))return!0;for(var b=this.children.slice(0),f=0,e=b.length;f<e;f++){var g=b[f];g.isVisible()&&(a.save(),g.presetContext(a),g.draw(a,c),a.restore())}return!0};b.update=function(){this.DisplayObject_update();
for(var a=this.children.slice(0),c=0,b=a.length;c<b;c++)a[c].update()};b.addChild=function(a){this.addChildAt(a,this.children.length)};b.addChildAt=function(a,c){0>c||c>this.children.length||null==a||(a.parent&&a.parent.removeChild(a),a.parent=this,a.root=this.root,this.children.splice(c,0,a))};b.removeChild=function(a){return this.removeChildAt(fanvas.indexOf(this.children,a))};b.removeChildAt=function(a){if(!(0>a||a>this.children.length-1)){var c=this.children[a];c&&(c.parent=null,c.uncache());
this.children.splice(a,1)}};b.removeAllChildren=function(){for(var a=this.children;a.length;)a.pop().parent=null};b.getChildAt=function(a){return this.children[a]};b.getChildByName=function(a){for(var c=this.children,b=0,f=c.length;b<f;b++)if(c[b].name==a)return c[b];return null};b.getChildIndex=function(a){return fanvas.indexOf(this.children,a)};b.getNumChildren=function(){return this.children.length};b.contains=function(a){for(;a;){if(a==this)return!0;a=a.parent}return!1};fanvas.Container=e})();
this.fanvas=this.fanvas||{};
(function(){var e=function(a,c,b){this.initialize(a,c,b)},b=e.prototype=new fanvas.Container;b.currentFrame=0;b.totalFrames=0;b.actionList=null;b.library=null;b.config=null;b._tweenList=null;b._remainList=null;b.Container_initialize=b.initialize;b.initialize=function(a,c,b){this.Container_initialize();this.library=a;this.config=b;this.currentFrame=0;a=this.library[c];this.totalFrames=a.totalFrames;this.actionList=a.frameActionList;this._tweenList=[];this._remainList=[]};b.Container_draw=b.draw;b.Container_update=
b.update;b.draw=function(a,c){if(!c&&this.drawFromCache(a))return!0;this.Container_draw(a,c);return!0};b.update=function(){this._updateTween();this._updateTimeline();this.Container_update()};b._updateTween=function(){for(var a=this._tweenList,c,b,f,e=this.root,g=0;g<a.length;g++){c=a[g];b=c.target;f=c.duration;e.dirtyRectList.push(b.dirtyRect);for(var n in c.tweenData)b[n]+=(c.tweenData[n]-b[n])/f;e.dirtyRectList.push(b.calculateDirtyRect());c.duration--;0==c.duration&&(a.splice(g,1),g--)}};b._updateTimeline=
function(){var a=this.currentFrame;if(0==a&&1<this.totalFrames){var c;for(0<this._remainList.length&&this._remainList.splice(0);0<this.getNumChildren();)c=this.getChildAt(0),0==c.initFrame&&this._remainList.push(c),this.removeChildAt(0);this._tweenList.splice(0)}c=this._getCurrentAction();if(null!=c&&c instanceof Array)for(var b=0;b<c.length;b++)this._exec(c[b]);a++;this.currentFrame=a==this.totalFrames?0:a};b._getCurrentAction=function(){for(var a=0;a<this.actionList.length;a++)if(this.actionList[a][0]==
this.currentFrame)return this.actionList[a].slice(1);return null};b._exec=function(a){this["_"+a[0]].apply(this,a.slice(1))};b._placeElement=function(a){var c=this.getChildByName(a.n);if(c)this.root.dirtyRectList.push(c.dirtyRect);else{if(void 0==a.id||-1==a.id||a.id>=this.library.length)return;var b=this.library[a.id];if(null==b)return;0==this.currentFrame&&(c=this._getFromList(a.n));if(!c){var f=b.rect;if("MC"==a.t)c=new fanvas.MovieClip(this.library,a.id,this.config);else{var c=new fanvas.Shape(b.graphics,
this.config),e=this.config.cache;if(e){var g=this.root.canvas;if(f.width>g.width||f.height>g.height)e=1;c.cache(f.x,f.y,f.width,f.height,e)}b.instance=c}c.rect=f;c.name=a.n;c.initFrame=this.currentFrame}c.clipDepth=a.cd||0;c.maskDepth=a.md||0;c.clipDepth?this._updateMaskRelation(c):c.mask=c.maskDepth?this._getMask(c):null;this.addChildAt(c,a.d)}c.setTransform(a.x,a.y,a.sX,a.sY,0,a.skX,a.skY);c.alpha=void 0!=a.a?a.a:1;a.shadow?c.shadow=new fanvas.Shadow(a.shadow.color,a.shadow.offsetX,a.shadow.offsetY,
a.shadow.blur):null!=c.shadow&&(c.shadow=null);if(a.filters&&0<a.filters.length){b=[];for(f=0;f<a.filters.length;f++)e=a.filters[f],"CF"==e.type?(e=new fanvas.ColorFilter(e.data[0],e.data[1],e.data[2],e.data[3],e.data[4],e.data[5],e.data[6],e.data[7]),b.push(e)):"CMF"==e.type?(e=new fanvas.ColorMatrixFilter(e.matrix),b.push(e)):"BF"==e.type&&(e=new fanvas.BlurFilter(e.blurX,e.blurY,e.quality),b.push(e));c.filters=b;a=c.rect;c.cache(a.x,a.y,a.width,a.height)}else c.filters&&0<c.filters.length&&c.uncache();
this.root.dirtyRectList.push(c.calculateDirtyRect())};b._removeElement=function(a){a=this.getChildByName(a);this.removeChild(a);this.root.dirtyRectList.push(a.dirtyRect)};b._tweenElement=function(a,b,d){if(a=this.getChildByName(a)){var c={};c.target=a;c.duration=b;c.tweenData=d;this._tweenList.push(c)}};b._updateMaskRelation=function(a){for(var b=0;b<this.children.length;b++){var d=this.children[b];a.clipDepth>d.maskDepth&&a.maskDepth<d.maskDepth&&(d.mask=a,this.root.dirtyRectList.push(d.dirtyRect),
d=d.calculateDirtyRect(),this.root.dirtyRectList.push(d))}};b._getMask=function(a){for(var b=0;b<this.children.length;b++){var d=this.children[b];if(d.clipDepth>a.maskDepth&&d.maskDepth<a.maskDepth)return d}return null};b._pE=b._placeElement;b._tE=b._tweenElement;b._rE=b._removeElement;b._getFromList=function(a){for(var b=0;b<this._remainList.length;b++)if(this._remainList[b].name==a)return this._remainList.splice(b,1)[0];return null};fanvas.MovieClip=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,b,d){this.initialize(a,b,d)},b=e.prototype=new fanvas.Container;b.canvas=null;b.swfData=null;b.config=null;b.dirtyRectList=[];b.dirtyThresholdArea=0;b.Container_initialize=b.initialize;b.initialize=function(a,b,d){this.config=d;this.swfData=b;this.Container_initialize();a=this.canvas="string"==typeof a?document.getElementById(a):a;b.bgColor&&this.canvas.setAttribute("style",(this.canvas.getAttribute("style")||"")+";background-color:"+b.bgColor);this.root=this;this._prebuildShapes(b.definitionPool);
var c=new fanvas.MovieClip(b.definitionPool,0,d);d.scale&&(c.scaleX=c.scaleY=d.scale);a.width=b.stageWidth*c.scaleX;a.height=b.stageHeight*c.scaleY;this.dirtyThresholdArea=a.width*a.height*2/3;c.globalMatrix=c.getMatrix();this.addChild(c);d.showFPS&&(this.stats=new fanvas.Stats(this.canvas.getContext("2d")))};b.update=function(a,b){if(this.canvas){var c=this.getChildAt(0),f=this.dirtyRectList=[];c.update();b||(f.length&&(b=this.canvas.getContext("2d"),b.setTransform(1,0,0,1,0,0),b.save(),this._clear(b,
f,1==c.currentFrame||!!this.config.clearAll),c.presetContext(b),c.draw(b,!1),this.config.showDirtyRect&&this._showDirtyRect(b,f,"#CC0000"),b.restore()),this.config.showFPS&&this.stats.update(a))}};b._clear=function(a,b,d){if(!(d=d||30<b.length)){for(var c=d=0;c<b.length;c++){var e=b[c];d+=e.width*e.height}d=d>this.dirtyThresholdArea}if(d)a.clearRect(0,0,this.canvas.width+1,this.canvas.height+1);else{for(d=0;d<b.length;d++)c=b[d],a.clearRect(c.x-1,c.y-1,c.width+2,c.height+2);a.beginPath();for(d=0;d<
b.length;d++)c=b[d],a.rect(c.x-1,c.y-1,c.width+2,c.height+2);a.clip()}};b._prebuildShapes=function(a){for(var b=0;b<a.length;b++){var d=a[b];if(d.graphics){var e=new fanvas.Shape(d.graphics,this.config);d.graphics=e.graphics}}};b._showDirtyRect=function(a,b,d){a.beginPath();for(var c=0;c<b.length;c++){var e=b[c];a.rect(e.x,e.y,e.width,e.height)}a.lineWidth=1;a.strokeStyle=d;a.stroke()};b.replay=function(){this.removeAllChildren();var a=new fanvas.MovieClip(this.swfData.definitionPool,0,this.config);
this.addChild(a);this.config.scale&&(a.scaleX=a.scaleY=this.config.scale);a.globalMatrix=a.getMatrix()};fanvas.Stage=e})();this.fanvas=this.fanvas||{};(function(){var e=function(){this.initialize()},b=e.prototype;b.initialize=function(){};b.getBounds=function(){return null};b.applyFilter=function(a,b,d,e,h,g,n,l){};fanvas.Filter=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,b,d){this.initialize(a,b,d)},b=e.prototype=new fanvas.Filter;b.initialize=function(a,b,d){if(isNaN(a)||0>a)a=0;this.blurX=a|0;if(isNaN(b)||0>b)b=0;this.blurY=b|0;if(isNaN(d)||1>d)d=1;this.quality=d|0};b.blurX=0;b.blurY=0;b.quality=1;b.mul_table=[1,171,205,293,57,373,79,137,241,27,391,357,41,19,283,265,497,469,443,421,25,191,365,349,335,161,155,149,9,278,269,261,505,245,475,231,449,437,213,415,405,395,193,377,369,361,353,345,169,331,325,319,313,307,301,37,145,285,281,69,
271,267,263,259,509,501,493,243,479,118,465,459,113,446,55,435,429,423,209,413,51,403,199,393,97,3,379,375,371,367,363,359,355,351,347,43,85,337,333,165,327,323,5,317,157,311,77,305,303,75,297,294,73,289,287,71,141,279,277,275,68,135,67,133,33,262,260,129,511,507,503,499,495,491,61,121,481,477,237,235,467,232,115,457,227,451,7,445,221,439,218,433,215,427,425,211,419,417,207,411,409,203,202,401,399,396,197,49,389,387,385,383,95,189,47,187,93,185,23,183,91,181,45,179,89,177,11,175,87,173,345,343,341,
339,337,21,167,83,331,329,327,163,81,323,321,319,159,79,315,313,39,155,309,307,153,305,303,151,75,299,149,37,295,147,73,291,145,289,287,143,285,71,141,281,35,279,139,69,275,137,273,17,271,135,269,267,133,265,33,263,131,261,130,259,129,257,1];b.shg_table=[0,9,10,11,9,12,10,11,12,9,13,13,10,9,13,13,14,14,14,14,10,13,14,14,14,13,13,13,9,14,14,14,15,14,15,14,15,15,14,15,15,15,14,15,15,15,15,15,14,15,15,15,15,15,15,12,14,15,15,13,15,15,15,15,16,16,16,15,16,14,16,16,14,16,13,16,16,16,15,16,13,16,15,16,
14,9,16,16,16,16,16,16,16,16,16,13,14,16,16,15,16,16,10,16,15,16,14,16,16,14,16,16,14,16,16,14,15,16,16,16,14,15,14,15,13,16,16,15,17,17,17,17,17,17,14,15,17,17,16,16,17,16,15,17,16,17,11,17,16,17,16,17,16,17,17,16,17,17,16,17,17,16,16,17,17,17,16,14,17,17,17,17,15,16,14,16,15,16,13,16,15,16,14,16,15,16,12,16,15,16,17,17,17,17,17,13,16,15,17,17,17,16,15,17,17,17,16,15,17,17,14,16,17,17,16,17,17,16,15,17,16,14,17,16,15,17,16,17,17,16,17,15,16,17,14,17,16,15,17,16,17,13,17,16,17,17,16,17,14,17,16,17,
16,17,16,17,9];b.getBounds=function(){var a=.5*Math.pow(this.quality,.6);return new fanvas.Rectangle(-this.blurX*a,-this.blurY*a,2*this.blurX*a,2*this.blurY*a)};b.applyFilter=function(a,b,d,e,h,g,n,l){g=g||a;null==n&&(n=b);null==l&&(l=d);try{var c=a.getImageData(b,d,e,h)}catch(M){return!1}a=this.blurX/2;if(isNaN(a)||0>a)return!1;a|=0;var f=this.blurY/2;if(isNaN(f)||0>f)return!1;f|=0;if(0==a&&0==f)return!1;var r=this.quality;if(isNaN(r)||1>r)r=1;r|=0;3<r&&(r=3);1>r&&(r=1);var k=c.data,m,p,u,t,x,y,
A,B,C,H,I,J,F=a+a+1;t=f+f+1;var K=e-1,G=h-1,E=a+1,D=f+1,L={r:0,b:0,g:0,a:0,next:null};b=L;for(m=1;m<F;m++)b=b.next={r:0,b:0,g:0,a:0,next:null};b.next=L;d=F={r:0,b:0,g:0,a:0,next:null};for(m=1;m<t;m++)d=d.next={r:0,b:0,g:0,a:0,next:null};for(d.next=F;0<r--;){x=t=0;var v=this.mul_table[a],z=this.shg_table[a];for(d=h;-1<--d;){y=E*(H=k[t]);A=E*(I=k[t+1]);B=E*(J=k[t+2]);C=E*(u=k[t+3]);b=L;for(m=E;-1<--m;)b.r=H,b.g=I,b.b=J,b.a=u,b=b.next;for(m=1;m<E;m++)p=t+((K<m?K:m)<<2),y+=b.r=k[p],A+=b.g=k[p+1],B+=b.b=
k[p+2],C+=b.a=k[p+3],b=b.next;m=L;for(b=0;b<e;b++)k[t++]=y*v>>>z,k[t++]=A*v>>>z,k[t++]=B*v>>>z,k[t++]=C*v>>>z,p=x+((p=b+a+1)<K?p:K)<<2,y-=m.r-(m.r=k[p]),A-=m.g-(m.g=k[p+1]),B-=m.b-(m.b=k[p+2]),C-=m.a-(m.a=k[p+3]),m=m.next;x+=e}v=this.mul_table[f];z=this.shg_table[f];for(b=0;b<e;b++){t=b<<2;y=D*(H=k[t]);A=D*(I=k[t+1]);B=D*(J=k[t+2]);C=D*(u=k[t+3]);d=F;for(m=0;m<D;m++)d.r=H,d.g=I,d.b=J,d.a=u,d=d.next;u=e;for(m=1;m<=f;m++)t=u+b<<2,y+=d.r=k[t],A+=d.g=k[t+1],B+=d.b=k[t+2],C+=d.a=k[t+3],d=d.next,m<G&&(u+=
e);t=b;m=F;if(0<r)for(d=0;d<h;d++)p=t<<2,k[p+3]=u=C*v>>>z,0<u?(k[p]=y*v>>>z,k[p+1]=A*v>>>z,k[p+2]=B*v>>>z):k[p]=k[p+1]=k[p+2]=0,p=b+((p=d+D)<G?p:G)*e<<2,y-=m.r-(m.r=k[p]),A-=m.g-(m.g=k[p+1]),B-=m.b-(m.b=k[p+2]),C-=m.a-(m.a=k[p+3]),m=m.next,t+=e;else for(d=0;d<h;d++)p=t<<2,k[p+3]=u=C*v>>>z,0<u?(u=255/u,k[p]=(y*v>>>z)*u,k[p+1]=(A*v>>>z)*u,k[p+2]=(B*v>>>z)*u):k[p]=k[p+1]=k[p+2]=0,p=b+((p=d+D)<G?p:G)*e<<2,y-=m.r-(m.r=k[p]),A-=m.g-(m.g=k[p+1]),B-=m.b-(m.b=k[p+2]),C-=m.a-(m.a=k[p+3]),m=m.next,t+=e}}g.putImageData(c,
n,l);return!0};fanvas.BlurFilter=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,b,d,e){this.initialize(a,b,d,e)},b=e.prototype;e.DELTA_INDEX=[0,.01,.02,.04,.05,.06,.07,.08,.1,.11,.12,.14,.15,.16,.17,.18,.2,.21,.22,.24,.25,.27,.28,.3,.32,.34,.36,.38,.4,.42,.44,.46,.48,.5,.53,.56,.59,.62,.65,.68,.71,.74,.77,.8,.83,.86,.89,.92,.95,.98,1,1.06,1.12,1.18,1.24,1.3,1.36,1.42,1.48,1.54,1.6,1.66,1.72,1.78,1.84,1.9,1.96,2,2.12,2.25,2.37,2.5,2.62,2.75,2.87,3,3.2,3.4,3.6,3.8,4,4.3,4.7,4.9,5,5.5,6,6.5,6.8,7,7.3,7.5,7.8,8,8.4,8.7,9,9.4,9.6,9.8,10];e.IDENTITY_MATRIX=
[1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1];e.LENGTH=e.IDENTITY_MATRIX.length;b.initialize=function(a,b,d,e){this.reset();this.adjustColor(a,b,d,e);return this};b.reset=function(){return this.copyMatrix(e.IDENTITY_MATRIX)};b.adjustColor=function(a,b,d,e){this.adjustHue(e);this.adjustContrast(b);this.adjustBrightness(a);return this.adjustSaturation(d)};b.adjustBrightness=function(a){if(0==a||isNaN(a))return this;a=this._cleanValue(a,255);this._multiplyMatrix([1,0,0,0,a,0,1,0,0,a,0,0,1,0,a,
0,0,0,1,0,0,0,0,0,1]);return this};b.adjustContrast=function(a){if(0==a||isNaN(a))return this;a=this._cleanValue(a,100);var b;0>a?b=127+a/100*127:(b=a%1,b=0==b?e.DELTA_INDEX[a]:e.DELTA_INDEX[a<<0]*(1-b)+e.DELTA_INDEX[(a<<0)+1]*b,b=127*b+127);this._multiplyMatrix([b/127,0,0,0,.5*(127-b),0,b/127,0,0,.5*(127-b),0,0,b/127,0,.5*(127-b),0,0,0,1,0,0,0,0,0,1]);return this};b.adjustSaturation=function(a){if(0==a||isNaN(a))return this;a=this._cleanValue(a,100);a=1+(0<a?3*a/100:a/100);this._multiplyMatrix([.3086*
(1-a)+a,.6094*(1-a),.082*(1-a),0,0,.3086*(1-a),.6094*(1-a)+a,.082*(1-a),0,0,.3086*(1-a),.6094*(1-a),.082*(1-a)+a,0,0,0,0,0,1,0,0,0,0,0,1]);return this};b.adjustHue=function(a){if(0==a||isNaN(a))return this;a=this._cleanValue(a,180)/180*Math.PI;var b=Math.cos(a);a=Math.sin(a);this._multiplyMatrix([.213+.787*b+-.213*a,.715+-.715*b+-.715*a,.072+-.072*b+.928*a,0,0,.213+-.213*b+.143*a,.715+b*(1-.715)+.14*a,.072+-.072*b+-.283*a,0,0,.213+-.213*b+-.787*a,.715+-.715*b+.715*a,.072+.928*b+.072*a,0,0,0,0,0,1,
0,0,0,0,0,1]);return this};b.concat=function(a){a=this._fixMatrix(a);if(a.length!=e.LENGTH)return this;this._multiplyMatrix(a);return this};b.toArray=function(){for(var a=[],b=0,d=e.LENGTH;b<d;b++)a[b]=this[b];return a};b.copyMatrix=function(a){for(var b=e.LENGTH,d=0;d<b;d++)this[d]=a[d];return this};b._multiplyMatrix=function(a){for(var b=[],d=0;5>d;d++){for(var e=0;5>e;e++)b[e]=this[e+5*d];for(e=0;5>e;e++){for(var h=0,g=0;5>g;g++)h+=a[e+5*g]*b[g];this[e+5*d]=h}}};b._cleanValue=function(a,b){return Math.min(b,
Math.max(-b,a))};b._fixMatrix=function(a){a instanceof e&&(a=a.toArray());a.length<e.LENGTH?a=a.slice(0,a.length).concat(e.IDENTITY_MATRIX.slice(a.length,e.LENGTH)):a.length>e.LENGTH&&(a=a.slice(0,e.LENGTH));return a};fanvas.ColorMatrix=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a,b,d,e,h,g,n,l){this.initialize(a,b,d,e,h,g,n,l)},b=e.prototype=new fanvas.Filter;b.redMultiplier=1;b.greenMultiplier=1;b.blueMultiplier=1;b.alphaMultiplier=1;b.redOffset=0;b.greenOffset=0;b.blueOffset=0;b.alphaOffset=0;b.initialize=function(a,b,d,e,h,g,n,l){this.redMultiplier=null!=a?a:1;this.greenMultiplier=null!=b?b:1;this.blueMultiplier=null!=d?d:1;this.alphaMultiplier=null!=e?e:1;this.redOffset=h||0;this.greenOffset=g||0;this.blueOffset=n||0;this.alphaOffset=l||0};
b.applyFilter=function(a,b,d,e,h,g,n,l){g=g||a;null==n&&(n=b);null==l&&(l=d);try{var c=a.getImageData(b,d,e,h)}catch(w){return!1}a=c.data;b=a.length;for(d=0;d<b;d+=4)a[d]=a[d]*this.redMultiplier+this.redOffset,a[d+1]=a[d+1]*this.greenMultiplier+this.greenOffset,a[d+2]=a[d+2]*this.blueMultiplier+this.blueOffset,a[d+3]=a[d+3]*this.alphaMultiplier+this.alphaOffset;g.putImageData(c,n,l);return!0};fanvas.ColorFilter=e})();this.fanvas=this.fanvas||{};
(function(){var e=function(a){this.initialize(a)},b=e.prototype=new fanvas.Filter;b.matrix=null;b.initialize=function(a){this.matrix=a};b.applyFilter=function(a,b,d,e,h,g,n,l){g=g||a;null==n&&(n=b);null==l&&(l=d);try{var c=a.getImageData(b,d,e,h)}catch(z){return!1}a=c.data;b=a.length;var f,r,k,m;f=this.matrix;d=f[0];e=f[1];h=f[2];for(var p=f[3],u=f[4],t=f[5],x=f[6],y=f[7],A=f[8],B=f[9],C=f[10],H=f[11],I=f[12],J=f[13],F=f[14],K=f[15],G=f[16],E=f[17],D=f[18],L=f[19],v=0;v<b;v+=4)f=a[v],r=a[v+1],k=a[v+
2],m=a[v+3],a[v]=f*d+r*e+k*h+m*p+u,a[v+1]=f*t+r*x+k*y+m*A+B,a[v+2]=f*C+r*H+k*I+m*J+F,a[v+3]=f*K+r*G+k*E+m*D+L;g.putImageData(c,n,l);return!0};fanvas.ColorMatrixFilter=e})();